/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numeros {
	int numero1;
	int numero2;
};
typedef struct numeros numeros;

#define PROGRAMA_CALCULADORA 0x31111111
#define VERSION_CALCULADORA 1

#if defined(__STDC__) || defined(__cplusplus)
#define suma 1
extern  int * suma_1(numeros *, CLIENT *);
extern  int * suma_1_svc(numeros *, struct svc_req *);
#define resta 2
extern  int * resta_1(numeros *, CLIENT *);
extern  int * resta_1_svc(numeros *, struct svc_req *);
#define multiplicacion 3
extern  int * multiplicacion_1(numeros *, CLIENT *);
extern  int * multiplicacion_1_svc(numeros *, struct svc_req *);
#define division 4
extern  float * division_1(numeros *, CLIENT *);
extern  float * division_1_svc(numeros *, struct svc_req *);
extern int programa_calculadora_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define suma 1
extern  int * suma_1();
extern  int * suma_1_svc();
#define resta 2
extern  int * resta_1();
extern  int * resta_1_svc();
#define multiplicacion 3
extern  int * multiplicacion_1();
extern  int * multiplicacion_1_svc();
#define division 4
extern  float * division_1();
extern  float * division_1_svc();
extern int programa_calculadora_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numeros (XDR *, numeros*);

#else /* K&R C */
extern bool_t xdr_numeros ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
